CREATE TABLE IF NOT EXISTS iot_product (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    product_key VARCHAR(64) NOT NULL,
    product_secret VARCHAR(64) NULL,
    name VARCHAR(128) NOT NULL,
    cover_image_url VARCHAR(512),
    thumbnail_url VARCHAR(512),
    description VARCHAR(512),
    protocol_type VARCHAR(32) NOT NULL DEFAULT 'MQTT_ALINK_JSON',
    device_type VARCHAR(32) NOT NULL DEFAULT 'DIRECT_DEVICE',
    status VARCHAR(16) NOT NULL DEFAULT 'enabled',
    extra_json TEXT,
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iot_product_tenant_pk (tenant_id, product_key),
    KEY idx_iot_product_tenant_name (tenant_id, name),
    KEY idx_iot_product_tenant_status (tenant_id, status)
);

CREATE TABLE IF NOT EXISTS iot_device (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    product_key VARCHAR(64) NOT NULL,
    device_key VARCHAR(64) NOT NULL,
    device_name VARCHAR(128) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'inactive',
    connect_status VARCHAR(32) NOT NULL DEFAULT 'disconnected',
    last_connected_at TIMESTAMP NULL,
    last_disconnected_at TIMESTAMP NULL,
    secret VARCHAR(128) NULL,
    protocol_type VARCHAR(32) NOT NULL DEFAULT 'MQTT_ALINK_JSON',
    protocol_version VARCHAR(32) NOT NULL DEFAULT '1.0',
    tags_json TEXT,
    meta_json TEXT,
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iot_device_tenant_pk_dk (tenant_id, product_key, device_key),
    KEY idx_iot_device_tenant_product (tenant_id, product_key),
    KEY idx_iot_device_tenant_status (tenant_id, status)
);

CREATE TABLE IF NOT EXISTS iot_thing_model (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    product_key VARCHAR(64) NOT NULL,
    model_json TEXT NOT NULL,
    version VARCHAR(32) NOT NULL DEFAULT 'v1',
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_iot_thing_model_tenant_product (tenant_id, product_key, updated_at)
);

CREATE TABLE IF NOT EXISTS iot_device_thing_model (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    product_key VARCHAR(64) NOT NULL,
    device_key VARCHAR(64) NOT NULL,
    model_json TEXT NOT NULL,
    version VARCHAR(32) NOT NULL DEFAULT 'v1',
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iot_device_thing_model_tenant_pk_dk (tenant_id, product_key, device_key),
    KEY idx_iot_device_thing_model_lookup (tenant_id, product_key, device_key)
);

CREATE TABLE IF NOT EXISTS iot_device_connect_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    product_key VARCHAR(64) NOT NULL,
    device_key VARCHAR(64) NOT NULL,
    action VARCHAR(16) NOT NULL,
    client_id VARCHAR(128),
    ip VARCHAR(64),
    user_agent VARCHAR(255),
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_iot_connect_record_lookup (tenant_id, product_key, device_key, created_at)
);

CREATE TABLE IF NOT EXISTS iot_device_property_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    product_key VARCHAR(64) NOT NULL,
    device_name VARCHAR(64) NOT NULL,
    property_identifier VARCHAR(128) NOT NULL,
    property_value TEXT,
    trace_id VARCHAR(64),
    message_id VARCHAR(64),
    topic VARCHAR(255),
    device_timestamp BIGINT,
    payload TEXT,
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_iot_prop_record_lookup (tenant_id, product_key, device_name, created_at),
    KEY idx_iot_prop_record_trace (tenant_id, trace_id)
);

CREATE TABLE IF NOT EXISTS iot_device_event_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    product_key VARCHAR(64) NOT NULL,
    device_name VARCHAR(64) NOT NULL,
    event_name VARCHAR(128) NOT NULL,
    trace_id VARCHAR(64),
    message_id VARCHAR(64),
    topic VARCHAR(255),
    device_timestamp BIGINT,
    payload TEXT,
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_iot_event_record_lookup (tenant_id, product_key, device_name, created_at),
    KEY idx_iot_event_record_trace (tenant_id, trace_id)
);

CREATE TABLE IF NOT EXISTS iot_device_service_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    product_key VARCHAR(64) NOT NULL,
    device_name VARCHAR(64) NOT NULL,
    service_name VARCHAR(128) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    trace_id VARCHAR(64),
    message_id VARCHAR(64),
    topic VARCHAR(255),
    device_timestamp BIGINT,
    payload TEXT,
    output_topic VARCHAR(255) NULL,
    output_device_timestamp BIGINT NULL,
    output_payload TEXT NULL,
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_iot_service_record_lookup (tenant_id, product_key, device_name, created_at),
    KEY idx_iot_service_record_trace (tenant_id, trace_id)
);

CREATE TABLE IF NOT EXISTS iot_device_group (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    group_key VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iot_device_group_tenant_gk (tenant_id, group_key),
    UNIQUE KEY uk_iot_device_group_tenant_name (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS iot_device_group_rel (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    group_key VARCHAR(64) NOT NULL,
    product_key VARCHAR(64) NOT NULL,
    device_key VARCHAR(64) NOT NULL,
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iot_device_group_rel (tenant_id, group_key, product_key, device_key),
    KEY idx_iot_device_group_rel_lookup (tenant_id, group_key, created_at),
    KEY idx_iot_device_group_rel_device (tenant_id, product_key, device_key)
);

CREATE TABLE IF NOT EXISTS iot_acl_policy (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    product_key VARCHAR(64) NOT NULL,
    subject_type VARCHAR(16) NOT NULL DEFAULT 'device',
    subject_value VARCHAR(64) NOT NULL,
    action VARCHAR(16) NOT NULL,
    topic_pattern VARCHAR(256) NOT NULL,
    effect VARCHAR(16) NOT NULL,
    priority INT NOT NULL DEFAULT 100,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    constraints_json TEXT,
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_iot_acl_policy_lookup (tenant_id, product_key, action, subject_type, subject_value, enabled, priority)
);

