CREATE TABLE IF NOT EXISTS iot_notify_settings (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    mail_enabled TINYINT(1) NOT NULL DEFAULT 0,
    smtp_host VARCHAR(256) NULL,
    smtp_port INT NULL,
    smtp_ssl TINYINT(1) NOT NULL DEFAULT 1,
    smtp_username VARCHAR(256) NULL,
    smtp_password VARCHAR(512) NULL,
    mail_from VARCHAR(256) NULL,
    mail_from_display VARCHAR(256) NULL,
    sms_enabled TINYINT(1) NOT NULL DEFAULT 0,
    sms_provider VARCHAR(32) NOT NULL DEFAULT 'ALIYUN',
    sms_access_key_id VARCHAR(256) NULL,
    sms_access_key_secret VARCHAR(512) NULL,
    sms_sign_name VARCHAR(128) NULL,
    sms_template_code VARCHAR(64) NULL,
    sms_region_id VARCHAR(64) NULL DEFAULT 'cn-hangzhou',
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iot_notify_settings_tenant (tenant_id)
);
