CREATE TABLE IF NOT EXISTS iot_alarm_notify_config (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    rule_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    remark VARCHAR(512) NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    email_enabled TINYINT(1) NOT NULL DEFAULT 0,
    sms_enabled TINYINT(1) NOT NULL DEFAULT 0,
    to_emails TEXT NULL,
    to_mobiles TEXT NULL,
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_alarm_notify_cfg_tenant_rule (tenant_id, rule_id),
    CONSTRAINT fk_alarm_notify_cfg_rule FOREIGN KEY (rule_id) REFERENCES iot_alarm_rule (id)
);

CREATE TABLE IF NOT EXISTS iot_alarm_notify_delivery (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    org_id BIGINT NULL,
    notify_config_id BIGINT NULL,
    rule_id BIGINT NOT NULL,
    alarm_event_id VARCHAR(64) NOT NULL,
    alarm_event_type VARCHAR(64) NOT NULL,
    channel VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    vendor_code VARCHAR(64) NULL,
    http_status INT NULL,
    error_message VARCHAR(1024) NULL,
    recipient_hint VARCHAR(512) NULL,
    is_test TINYINT(1) NOT NULL DEFAULT 0,
    is_delete TINYINT(1) NOT NULL DEFAULT 0,
    create_user VARCHAR(64) NULL,
    update_user VARCHAR(64) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_alarm_notify_del_tenant_created (tenant_id, created_at),
    KEY idx_alarm_notify_del_cfg (notify_config_id),
    KEY idx_alarm_notify_del_rule (rule_id),
    CONSTRAINT fk_alarm_notify_del_cfg FOREIGN KEY (notify_config_id) REFERENCES iot_alarm_notify_config (id) ON DELETE SET NULL
);
